---
- name: Playbook to install general tools
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  vars:
    TFROM: 1.13.5
  tasks:
    - name: check the hostnames
      shell: cat /etc/lsb-release
    - name: perform apt update
      shell: apt update -y
    - name: install general tools
      shell: apt install unzip jq stress net-tools -y